hmrc/amls

- app/models/fe/SubscriptionView.scala
- app/models/fe/moneyservicebusiness/SendTheLargestAmountsOfMoney.scala
- test/models/fe/SubscriptionViewSpec.scala
- test/models/fe/moneyservicebusiness/SendTheLargestAmountsOfMoneySpec.scala
this should fix Fit and proper failure s4 and unable to log in after amendments s6
> fixed type of MoneyServiceBusiness

- app/models/des/aboutyou/Aboutyou.scala
- app/models/des/aboutyou/DeclarationRoles.scala
- app/models/fe/declaration/AddPerson.scala
- app/models/fe/declaration/RoleWithinBusinessRelease7.scala
- test/models/des/aboutyou/AboutYouSpec.scala
- test/models/fe/declaration/AddPersonSpec.scala
This pull request adds the models for the changes to the filing individual for the release 7 schema.  No conversions yet, and no actual use of the models (so no toggling yet).
> Amls 1233 part 1

- test/connectors/AmendVariationDESConnectorSpec.scala
Fix the jenkin build failure for amls amend variation connector
> Fix the jenkin build failure for amls amend variation connector

- app/services/AmendVariationService.scala
- app/services/SubscriptionService.scala
- conf/resources/API4_Request.json
- conf/resources/API6_Request.json
- project/MicroService.scala
- project/MicroServiceBuild.scala
- test/services/AmendVariationServicePreRelease7Spec.scala
- test/services/AmendVariationServiceSpec.scala
- test/services/SubscriptionServiceSpec.scala
validates before submission using a 3rd party library. Removed email validation from schemas as reference to external email validation doesn't seem to work here.
> Add schema validation

- app/audit/SubscriptionEvent.scala
- app/models/des/hvd/Hvd.scala
- app/services/AmendVariationService.scala
- test/models/des/DesConstants.scala
- test/models/des/hvd/HvdSpec.scala
- test/services/AmendVariationServiceSpec.scala
Also includes the work to add auditing into variation/renewal schema failures.
> AMLS-3179: Defaulted percentageOfCashPaymentOver15000 to 0

- app/repositories/FeesRepository.scala
- app/repositories/PaymentRepository.scala
- app/services/PaymentService.scala
- app/utils/MongoUtils.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
These libraries have been upgraded according to the tax catalogue. This commit also contains an upgrade to playReactiveMongo which required some code changes to accommodate it.
> Upgraded library versions

- app/config/AmlsConfig.scala
- app/connectors/EnrolmentStoreConnector.scala
- conf/application.conf
- test/connectors/EnrolmentStoreConnectorSpec.scala
Depends on:
https://github.com/hmrc/amls-stub/pull/49
> Initial commit - switch to tax enrolments service from enrolments store

- conf/application.conf
- project/MicroService.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
https://catalogue.tax.service.gov.uk/service/amls
> Bumped libary versions according to service catalogue

- app/models/des/responsiblepeople/RPExtra.scala
- test/models/des/responsiblepeople/RPExtraSpec.scala
Corrected the status, as deleted people were previously going through to DES as updated
Also added additional unit tests.
AMLS changes only - no impact on FrontEnd
- Created additional unit test cases
- Run unit test suite.
- Manual testing of added, changed, unchanged and deleted responsible people, and the associated des messages via stubs.
**Will need to be integration tested on QA**
> AMLS-4101:Corrected status on deleted people

- app/connectors/AmendVariationDESConnector.scala
- app/controllers/AmendVariationController.scala
- project/MicroService.scala
- project/plugins.sbt
> Added required config for new build process

- app/connectors/AmendVariationDESConnector.scala
- app/controllers/AmendVariationController.scala
- project/MicroServiceBuild.scala
> Remove dependency that was not required

- app/config/AmlsConfig.scala
- app/connectors/AmendVariationDESConnector.scala
- app/controllers/AmendVariationController.scala
- app/models/des/responsiblepeople/IdDetail.scala
- app/models/des/responsiblepeople/NationalityDetails.scala
- app/models/des/responsiblepeople/ResponsiblePersons.scala
- app/models/des/responsiblepeople/UkResident.scala
- app/models/fe/responsiblepeople/DateOfBirth.scala
- app/models/fe/responsiblepeople/ResponsiblePeople.scala
- app/utils/ResponsiblePeopleUpdateHelper.scala
- conf/application.conf
- test/models/DefaultDesValues.scala
- test/models/DefaultFEValues.scala
- test/models/des/DesConstants.scala
- test/models/des/responsiblepeople/NationalityDetailsSpec.scala
- test/models/des/responsiblepeople/ResponsiblePersonsSpec.scala
- test/models/des/responsiblepeople/UkResidentSpec.scala
- test/models/fe/responsiblepeople/DateOfBirthSpec.scala
- test/models/fe/responsiblepeople/NonUKPassportSpec.scala
- test/models/fe/responsiblepeople/PositionWithinBusinessSpec.scala
- test/models/fe/responsiblepeople/ResponsiblePeopleSpec.scala
- test/models/fe/responsiblepeople/ResponsiblePersonAddressHistorySpec.scala
- test/models/fe/responsiblepeople/UKPassportSpec.scala
- test/services/AmendVariationServiceSpec.scala
- test/services/SubscriptionServiceSpec.scala
Phase2 changes for Date Of Birth field.
Date of birth field for all Responsible Persons AMLS-Stub and AMLS-Frontend
Unit tests, with toggle on and off for phase-2-changes
> AMLS-4288 | Date of birth field for all Responsible Persons part 3 - AMLS

- test/controllers/SubscriptionViewControllerSpec.scala
- test/models/des/AmendVariationRequestSpec.scala
- test/models/des/SubscriptionRequestSpec.scala
- test/models/fe/SubscriptionViewSpec.scala
update to failing unit tests when phase-2-changes is set to true.
@JGRobinson please, can you check this and merge with AMLS-4330
> Amls 4330 fix remaining tests

- test/models/DefaultFEValues.scala
- test/models/fe/responsiblepeople/ResponsiblePeopleSpec.scala
some field got dropped by the merge from yesterday
> restored some lost field due to the merge horror from yesterday

- conf/application.conf
> toggle update to test staging

- app/audit/SubscriptionEvent.scala
- app/connectors/AmendVariationDESConnector.scala
- app/connectors/SubscribeDESConnector.scala
- test/connectors/AmendVariationDESConnectorSpec.scala
- test/connectors/SubscribeDESConnectorSpec.scala
This PR adds more detail to the DES API calls around error conditions. If a 400 error is encountered for example; the response body should contain a reason. Currently this is not fed into splunk for all API activity around APIs 4 and 6. 
Local testing, unit tests added and acceptance tests run. 
We should get this change into staging and QA and verify the data is being output. This extra splunk logging will help us debug DES failures for phase 2.
> Amls 4444 splunk

- app/config/AmlsGlobal.scala
- test/connectors/SubscribeDESConnectorSpec.scala
added code so the 400 response wont get converted to a 500
> AMLS-4464 added unit test around BAD_REQUEST

- app/audit/AmendVariationAuditModel.scala
- app/audit/SubscriptionEvent.scala
Add request to audit events for;
case "Amendment" => "amendmentSubmitted"
case "Variation" => "variationSubmitted"
case "Renewal"  => "renewalSubmitted"
case "Renewal Amendment" => "renewalAmendmentSubmitted"
val auditModel = AmendVariationAuditModel(amlsRegistrationNumber,
response.paymentReference,
request.acknowledgementReference,
request.businessDetails.typeOfLegalEntity,
request.changeIndicators,
request
)
> Add more audit events for renewals and amendments

- app/audit/KnownFactsEvent.scala
- app/audit/SubscriptionEvent.scala
- app/audit/SubscriptionStatusEvent.scala
- app/audit/SubscriptionViewEvent.scala
- app/config/AmlsConfig.scala
- app/config/AmlsGlobal.scala
- app/config/wiring.scala
- app/connectors/DESConnector.scala
- app/connectors/EnrolmentStoreConnector.scala
- app/connectors/GovernmentGatewayAdminConnector.scala
- app/connectors/PayAPIConnector.scala
- app/utils/AuditHelper.scala
- conf/application.conf
- project/MicroServiceBuild.scala
- project/plugins.sbt
- test/connectors/PayAPIConnectorSpec.scala
- test/utils/AuditHelperSpec.scala
update to amls to compile with play framework version 2.5.19.
all unit tests and acceptance-tests have been ran and they all pass
> Amls 4620 - play updgrade to 2.5.19

- conf/application.conf
> Add health check config

- app/services/AmendVariationService.scala
- app/services/SubscriptionService.scala
> Fix logging

- .github/PULL_REQUEST_TEMPLATE.md
- generate-my-release-note.sh
- generate-release-notes.sh
- release_notes/AMLS-4697.txt
N/A
Local testing and group demo
> Added scripts to track and generate release notes

- app/models/des/bankdetails/BankDetailsView.scala
- test/audit/MockAudit.scala
- test/models/des/bankaccountdetails/BankAccountViewSpec.scala
https://github.com/hmrc/amls-stub/pull/110
Unit and Acceptance and Manual with: https://github.com/hmrc/amls-stub/pull/110
> AMLS-4698 - Fix to cap number of bank accounts to 99 to prevent schema validation error

- release_notes/AMLS-4697.txt
- release_notes/releases/v4.116.0/v4.116.0-21-02-2019.txt
Generate release notes for v4.116.0
N/A
N/A
> Generate release notes for v4.116.0

- conf/application.conf
- release_notes/AMLS-4775.txt
Specify play http parser max memory buffer in line with DES limit
https://github.com/hmrc/amls-stub/pull/116
Local + Unit + acceptance tests
> Specify play http parser max memory buffer in line with DES limit

- app/models/fe/supervision/AnotherBody.scala
- release_notes/AMLS-4272.txt
- test/models/fe/supervision/AnotherBodySpec.scala
Backend changes for supervision section page split. Changes in AnotherBody model.
- PR in frontend need to be merged at the same time
- unit test
- manual tests
> Amls 4272 - Supervision Section page split

- generate-release-notes.sh
Change release notes script to prompt for release tag
N/A
Local
> Change release notes script to prompt for release tag

- release_notes/AMLS-4123.txt
- release_notes/releases/v4.136.0/v4.136.0-05-04-2019.txt
As above.
- none
- not applicable
> Generated release notes for release 4.136.0

- generate-my-release-note.sh
- release_notes/AMLS-4198.txt
- release_notes/AMLS-4626.txt
- release_notes/AMLS-4892.txt
- release_notes/releases/v4.116.0/v4.116.0-21-02-2019.txt
- release_notes/releases/v4.119.0/v4.119.0-13-03-2019.txt
- release_notes/releases/v4.125.0/v4.125.0-20-03-2019.txt
- release_notes/releases/v4.136.0/v4.136.0-05-04-2019.txt
Remove url from release notes
N/A
Local
> Update release notes to rmeove url

- release_notes/AMLS-4198.txt
- release_notes/AMLS-4626.txt
- release_notes/AMLS-4892.txt
- release_notes/releases/4.144.0/4.144.0-16-04-2019.txt
Generate release notes
N/A
N/A
> Generate release notes

- test/connectors/RegistrationDetailsDesConnectorSpec.scala
Fix failing build by adding fixture for one app per suite to work
N/A
Local / Unit
> Fix failing build by adding fixture for one app per suite to work

- app/controllers/FeeResponseController.scala
- app/modules/Module.scala
- app/repositories/FeesRepository.scala
- conf/app.routes
- test/controllers/FeesControllerSpec.scala
Refactor Fee Response Controller to use DI
N/A
Unit and Regression Pack
> Refactor Fee Response Controller to use DI

- app/controllers/SubscriptionController.scala
In PR AMLS-5022 #262 there was probably accidentally removed one of the imports, because of that compilation fails. 
- none
- unit test run
> AMLS-5022 | Added missing import

- release_notes/AMLS-5022.txt
- release_notes/releases/v4.162.0/v4.162.0-24-07-2019.txt
Like above.
- none
- not applicable
> Release 4.162.0 release notes

- app/audit/AmendVariationAuditModel.scala
- app/audit/SubscriptionEvent.scala
- release_notes/AMLS-5247.txt
- test/connectors/AmendVariationDESConnectorSpec.scala
Changed payment reference call to AmendVariationResponse within AmendVariationAuditModel with a new test
Unit Test
> AMLS-5247 | Added AmendVariationResponse to AuditModel

- app/models/des/responsiblepeople/RPExtra.scala
- app/utils/ResponsiblePeopleUpdateHelper.scala
- release_notes/AMLS-5332.txt
- test/models/des/responsiblepeople/RPExtraSpec.scala
Renamed and added fields to RPExtra class, updated readers and writers, specs.
- none
- unit tests, regression
>  AMLS-5332 | CR32: Handling additional fields in responsible people part of schema

- app/models/des/aboutthebusiness/PreviouslyRegisteredMLR.scala
- app/models/des/aboutthebusiness/PreviouslyRegisteredMLRView.scala
- app/models/fe/businessdetails/PreviouslyRegistered.scala
- release_notes/AMLS-4578.txt
- test/models/DefaultFEValues.scala
- test/models/des/SubscriptionRequestSpec.scala
- test/models/des/aboutthebusiness/BusinessContactDetailsSpec.scala
- test/models/des/aboutthebusiness/CorporationTaxRegisteredCbUbLlpSpec.scala
- test/models/des/aboutthebusiness/PreviouslyRegisteredSpec.scala
- test/models/fe/businessdetails/BusinessDetailsSpec.scala
- test/models/fe/businessdetails/PreviouslyRegisteredSpec.scala
Updated "Is your business currently registered with HMRC?"'
https://github.com/hmrc/amls-frontend/pull/1222
Manual testing and unit tests
> AMLS-4578 | Updated "Is your business currently registered with HMRC?"

- app/models/des/amp/Amp.scala
- app/models/fe/amp/AmpData.scala
^^ ONLY MERGE with other AMLS-5479 branches
Unit
Manually
> AMLS-5479 | Changed AMP data being sent by removing Bought

- conf/resources/api6_schema_release_4.2.0.json
> Updated api6

- release_notes/AMLS-4578.txt
- release_notes/AMLS-5247.txt
- release_notes/AMLS-5292.txt
- release_notes/AMLS-5332.txt
- release_notes/AMLS-5334.txt
- release_notes/AMLS-5346.txt
- release_notes/AMLS-5401.txt
- release_notes/releases/v4.182.0/v4.182.0-16-12-2019.txt
Generate release notes for v4.182.0
N/A
N/A
> Generate release notes for v4.182.0

- app/connectors/PayAPIConnector.scala
- app/models/payapi/Payment.scala
- app/models/payments/Payment.scala
- app/services/PaymentService.scala
- release_notes/AMLS-5587.txt
- test/connectors/PayAPIConnectorSpec.scala
- test/generators/PayApiGenerator.scala
- test/models/payapi/PaymentSpec.scala
- test/models/payments/PaymentSpec.scala
- test/services/PaymentServiceSpec.scala
> Revert "Amls 5587" - Pay API changes

- project/MicroServiceBuild.scala
Upgraded mongo version to 7.22.0
- none
- unit tests
> Upgraded mongo version to 7.22.0

- app/exceptions/HttpStatusException.scala
- release_notes/AMLS-5720.txt
Fix to correctly handle http exceptions
N/A
Local
> Fix to correctly handle http exceptions

- release_notes/AMLS-5657.txt
- release_notes/AMLS-5697.txt
- release_notes/AMLS-5736.txt
- release_notes/releases/v4.205.0/v4.205.0-04-03-2020.txt
> Added release notes

- app/models/des/tcsp/TcspAll.scala
- app/models/fe/tcsp/Tcsp.scala
- release_notes/AMLS-5664.txt
- test/models/DefaultFEValues.scala
- test/models/des/tcsp/TcspAllSpec.scala
- test/models/fe/tcsp/TcspSpec.scala
Amended TCSP backend des/fe models to allow for correct value to be passed through on user submission
Unit 
Manual - Loaded 3 separate users with yes/no flows on new branch and compared with master to check format is still correct and values have changed.
> AMLS-4981 | Fixed TCSP bug and amended unit tests

- app/services/AmendVariationService.scala
- app/services/SubscriptionService.scala
- conf/resources/api4_schema_release_5.1.0.json
- conf/resources/api6_schema_release_5.1.0.json
- test/services/AmendVariationServiceSpec.scala
Added latest schemas for use with phase 3 toggle on
N/A
Unit
> Added latest schemas for use with phase 3 toggle on

- app/models/des/businessactivities/EabServices.scala
- test/models/des/AmendVariationRequestSpec.scala
- test/models/des/SubscriptionRequestSpec.scala
- test/models/des/businessActivities/EabServicesSpec.scala
> Revert "Fix build"

- app/services/AmendVariationService.scala
- app/services/SubscriptionService.scala
- conf/resources/api4_schema_release_5.1.0.json
- conf/resources/api6_schema_release_5.1.0.json
- test/services/AmendVariationServiceSpec.scala
> Revert "Revert "Added latest schemas for use with phase 3 toggle on""

- app/models/des/businessactivities/EabServices.scala
- test/models/des/AmendVariationRequestSpec.scala
- test/models/des/SubscriptionRequestSpec.scala
- test/models/des/businessActivities/EabServicesSpec.scala
Re-introduce :
https://github.com/hmrc/amls/pull/297
> Re-introduce PR 297

- app/models/fe/tcsp/ServicesOfAnotherTCSP.scala
- release_notes/AMLS-5874.txt
- test/models/des/DesConstants.scala
- test/models/fe/tcsp/TcspSpec.scala
Live TCSP issue - Services of another TCSP with no MLR
N/A
Unit + Local
> Re raised PR as rebase did not work

- app/models/des/tradingpremises/PremisesDetails.scala
- release_notes/AMLS-5914.txt
- test/models/des/tradingpremises/PremisesDetailsSpec.scala
> Amls 5914 | Bug fix: msb services switched during conversion

- release_notes/AMLS-5779.txt
- release_notes/AMLS-5848.txt
- release_notes/AMLS-5914.txt
- release_notes/releases/v4.225.0/v4.225.0-19-05-2020.txt
Added release notes for v4.225.0
> Added release notes for v4.225.0

- project/MicroServiceBuild.scala
- project/build.properties
- project/plugins.sbt
- release_notes/AMLS-5750.txt
> Amls 5750 | Updated app dependencies

- app/models/des/responsiblepeople/ResponsiblePersons.scala
- release_notes/AMLS-5917.txt
Remove TODO from code
N/A
Unit
> AMLS-5917 | Remove TODO from code

- app/connectors/PayAPIConnector.scala
- app/connectors/SubscribeDESConnector.scala
> DLS-5535 remove println statements leaking info

- app/models/des/tcsp/TcspAll.scala
- app/models/fe/tcsp/ServicesOfAnotherTCSP.scala
- test/models/DefaultFEValues.scala
- test/models/des/tcsp/TcspAllSpec.scala
- test/models/fe/tcsp/ServicesOfAnotherTCSPSpec.scala
- test/models/fe/tcsp/TcspSpec.scala
> DDCYLS-5260 Updating TCSP MLR number to be optional

- README.md
> DDCYLS-6374 - ReadMe update 

- app/connectors/AmendVariationDESConnector.scala
- app/connectors/DeregisterSubscriptionConnector.scala
- app/connectors/EnrolmentStoreConnector.scala
- app/connectors/GovernmentGatewayAdminConnector.scala
- app/connectors/PayAPIConnector.scala
- app/connectors/RegistrationDetailsDesConnector.scala
- app/connectors/SubscribeDESConnector.scala
- app/connectors/SubscriptionStatusDESConnector.scala
- app/connectors/ViewDESConnector.scala
- app/connectors/WithdrawSubscriptionConnector.scala
- conf/application.conf
- project/AppDependencies.scala
- test/connectors/AmendVariationDESConnectorSpec.scala
- test/connectors/DeregisterSubscriptionConnectorSpec.scala
- test/connectors/EnrolmentStoreConnectorSpec.scala
- test/connectors/GovernmentGatewayAdminConnectorSpec.scala
- test/connectors/PayAPIConnectorSpec.scala
- test/connectors/RegistrationDetailsDesConnectorSpec.scala
- test/connectors/SubscribeDESConnectorSpec.scala
- test/connectors/SubscriptionStatusDESConnectorSpec.scala
- test/connectors/ViewDESConnectorSpec.scala
- test/connectors/WithdrawSubscriptionConnectorSpec.scala
- test/utils/AmlsBaseSpec.scala
Updated the httpclient to v2 and test cases
> Ddcyls-6439: Updated the httpclient to v2 and test cases
